### Create Menu Item
POST localhost:8081/api/v1/menus
Content-Type: application/json

{
  "title": "Fried Chicken 2",
  "description": "Menu 1 description",
  "nutritionValue": 100
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 200");
    });
%}

### Get Menu Item
GET localhost:8081/api/v1/menus/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Menu Item
PUT localhost:8081/api/v1/menus/1
Content-Type: application/json

{
  "nutritionValue": 400
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Menu Item
DELETE localhost:8081/api/v1/menus/2
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}